if(NOT DEFINED MODE)
    message(FATAL_ERROR "CleanupStaleEntries.cmake requires MODE")
endif()

if(NOT DEFINED AIO_DIR)
    message(FATAL_ERROR "CleanupStaleEntries.cmake requires AIO_DIR")
endif()

if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "CleanupStaleEntries.cmake requires SOURCE_DIR")
endif()

# Read feature paths from a file (one path per line) to avoid command-line
# quoting issues with paths that contain spaces.
macro(read_paths_file _var _file_var)
    set(${_var} "")
    if(DEFINED ${_file_var} AND EXISTS "${${_file_var}}")
        file(STRINGS "${${_file_var}}" ${_var})
    endif()
endmacro()

if(MODE STREQUAL "AIO")
    read_paths_file(FEATURE_PATHS FEATURE_PATHS_FILE)

    file(GLOB_RECURSE _current_aio_sources LIST_DIRECTORIES FALSE "${SOURCE_DIR}/package/*")
    list(FILTER _current_aio_sources EXCLUDE REGEX "/Tests/")
    list(FILTER _current_aio_sources EXCLUDE REGEX "/Shaders/")

    foreach(_fpath IN LISTS FEATURE_PATHS)
        if(EXISTS "${_fpath}")
            file(GLOB_RECURSE _tmp LIST_DIRECTORIES FALSE "${_fpath}/*")
            list(FILTER _tmp EXCLUDE REGEX "/Tests/")
            list(FILTER _tmp EXCLUDE REGEX "/Shaders/")
            list(APPEND _current_aio_sources ${_tmp})
        endif()
    endforeach()

    set(_current_aio_rels)
    foreach(_src IN LISTS _current_aio_sources)
        if(_src MATCHES "^${SOURCE_DIR}/package/")
            file(RELATIVE_PATH _rel "${SOURCE_DIR}/package" "${_src}")
            list(APPEND _current_aio_rels "${_rel}")
        else()
            foreach(_fpath IN LISTS FEATURE_PATHS)
                string(FIND "${_src}" "${_fpath}" _is_feature_path)
                if(NOT _is_feature_path EQUAL -1)
                    file(RELATIVE_PATH _rel "${_fpath}" "${_src}")
                    list(APPEND _current_aio_rels "${_rel}")
                    break()
                endif()
            endforeach()
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _current_aio_rels)

    file(GLOB_RECURSE _existing_aio_files LIST_DIRECTORIES FALSE "${AIO_DIR}/*")
    set(_stale_aio_files)
    foreach(_existing IN LISTS _existing_aio_files)
        file(RELATIVE_PATH _rel "${AIO_DIR}" "${_existing}")
        if(NOT _rel MATCHES "^SKSE/Plugins/" AND NOT _rel MATCHES "^Shaders/")
            list(FIND _current_aio_rels "${_rel}" _idx)
            if(_idx EQUAL -1)
                list(APPEND _stale_aio_files "${_existing}")
            endif()
        endif()
    endforeach()

    foreach(_stale IN LISTS _stale_aio_files)
        file(REMOVE "${_stale}")
    endforeach()

elseif(MODE STREQUAL "SHADERS")
    read_paths_file(FEATURE_SHADER_PATHS FEATURE_SHADER_PATHS_FILE)

    file(GLOB_RECURSE _package_shaders LIST_DIRECTORIES FALSE "${SOURCE_DIR}/package/Shaders/*")
    list(FILTER _package_shaders EXCLUDE REGEX "/Tests/")

    set(_current_shader_rels)
    foreach(_src IN LISTS _package_shaders)
        file(RELATIVE_PATH _rel "${SOURCE_DIR}/package/Shaders" "${_src}")
        list(APPEND _current_shader_rels "${_rel}")
    endforeach()

    foreach(_shader_path IN LISTS FEATURE_SHADER_PATHS)
        if(EXISTS "${_shader_path}")
            file(GLOB_RECURSE _feat_shaders LIST_DIRECTORIES FALSE "${_shader_path}/*")
            list(FILTER _feat_shaders EXCLUDE REGEX "/Tests/")
            foreach(_src IN LISTS _feat_shaders)
                file(RELATIVE_PATH _rel "${_shader_path}" "${_src}")
                list(APPEND _current_shader_rels "${_rel}")
            endforeach()
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _current_shader_rels)

    file(GLOB_RECURSE _aio_shaders LIST_DIRECTORIES FALSE "${AIO_DIR}/Shaders/*")
    set(_stale_shader_files)
    foreach(_existing IN LISTS _aio_shaders)
        file(RELATIVE_PATH _rel "${AIO_DIR}/Shaders" "${_existing}")
        list(FIND _current_shader_rels "${_rel}" _idx)
        if(_idx EQUAL -1)
            list(APPEND _stale_shader_files "${_existing}")
        endif()
    endforeach()

    foreach(_stale IN LISTS _stale_shader_files)
        file(REMOVE "${_stale}")
    endforeach()
else()
    message(FATAL_ERROR "CleanupStaleEntries.cmake MODE must be AIO or SHADERS")
endif()
