if(NOT DEFINED SOURCE_DIR OR NOT IS_DIRECTORY "${SOURCE_DIR}")
    message(FATAL_ERROR "SOURCE_DIR must name the Community Shaders source directory")
endif()
if(NOT DEFINED STAGE_DIR OR NOT IS_DIRECTORY "${STAGE_DIR}")
    message(FATAL_ERROR "STAGE_DIR must name an existing package staging directory")
endif()
if(NOT DEFINED INCLUDE_ALL)
    set(INCLUDE_ALL OFF)
endif()

include("${SOURCE_DIR}/cmake/PackageNotices.cmake")
cs_normalize_package_notices("${SOURCE_DIR}" "${STAGE_DIR}" "${INCLUDE_ALL}")
